project_id = "mutulosksodfkpdfkkhl"

[functions.create-donation-checkout]
verify_jwt = false

[functions.approve-member]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.submit-member-application]
verify_jwt = false

[functions.create-campaign-donation]
verify_jwt = false

[functions.verify-campaign-donation]
verify_jwt = false

[functions.get-campaign-total]
verify_jwt = false
