import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "EN" | "ES";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  "nav.home": { EN: "Home", ES: "Inicio" },
  "nav.about": { EN: "About", ES: "Nosotros" },
  "nav.ourWork": { EN: "Our Work", ES: "Nuestro Trabajo" },
  "nav.blog": { EN: "Blog", ES: "Blog" },
  "nav.resources": { EN: "Resources", ES: "Recursos" },
  "nav.getInvolved": { EN: "Get Involved", ES: "Participa" },
  "nav.contact": { EN: "Contact", ES: "Contacto" },
  "nav.donate": { EN: "Donate", ES: "Donar" },

  // Hero Section - Index
  "hero.badge": { EN: "Non-partisan community NGO for Cuban migrants", ES: "ONG comunitaria no partidista para migrantes cubanos" },
  "hero.title": { EN: "Defending the Cuban Adjustment Act and the right to freedom", ES: "Defendiendo la Ley de Ajuste Cubano y el derecho a la libertad" },
  "hero.description": { EN: "We defend the <strong>humane application of the Cuban Adjustment Act (CAA)</strong> so Cuban migrants and their families can obtain stability and legal status. Cuba is currently designated by the United States as a <strong>State Sponsor of Terrorism</strong>, reflecting a serious situation for human rights and security. Many people are fleeing repression and need protection and fair treatment.", ES: "Defendemos la <strong>aplicación humanitaria de la Ley de Ajuste Cubano (CAA)</strong> para que los migrantes cubanos y sus familias puedan obtener estabilidad y estatus legal. Cuba está actualmente designada por Estados Unidos como <strong>Estado Patrocinador del Terrorismo</strong>, reflejando una situación grave para los derechos humanos y la seguridad. Muchas personas huyen de la represión y necesitan protección y trato justo." },
  "hero.bullet1": { EN: "Legal information and civic education for Cuban migrants and their families.", ES: "Información legal y educación cívica para migrantes cubanos y sus familias." },
  "hero.bullet2": { EN: "Monitoring abuses, fraud, and misuse of immigration processes.", ES: "Monitoreo de abusos, fraude y mal uso de procesos migratorios." },
  "hero.bullet3": { EN: "Community support, ambassadors, and local outreach across the United States.", ES: "Apoyo comunitario, embajadores y alcance local en Estados Unidos." },
  "hero.learnMore": { EN: "Learn more about our mission", ES: "Conoce más sobre nuestra misión" },

  // Who We Are Section
  "whoWeAre.title": { EN: "Who we are", ES: "Quiénes somos" },
  "whoWeAre.description": { EN: "We are formed by Cuban migrants, professionals, and allies committed to <strong>justice, dignity, and civic education</strong>. We operate as a non-profit under Florida law (Chapter 617 of the Florida Statutes) and are eligible for 501(c)(3) status. All resources are dedicated exclusively to institutional purposes.", ES: "Estamos formados por migrantes cubanos, profesionales y aliados comprometidos con la <strong>justicia, dignidad y educación cívica</strong>. Operamos como una organización sin fines de lucro bajo la ley de Florida (Capítulo 617 de los Estatutos de Florida) y somos elegibles para el estatus 501(c)(3). Todos los recursos se dedican exclusivamente a propósitos institucionales." },
  "whoWeAre.mission": { EN: "Mission", ES: "Misión" },
  "whoWeAre.missionDesc": { EN: "Promote social justice and human dignity for immigrants, especially Cubans, through civic education, community assistance, and social integration.", ES: "Promover la justicia social y la dignidad humana para los inmigrantes, especialmente los cubanos, a través de la educación cívica, asistencia comunitaria e integración social." },
  "whoWeAre.vision": { EN: "Vision", ES: "Visión" },
  "whoWeAre.visionDesc": { EN: "Be a reference organization in education, freedom, and solidarity with immigrants, recognized for transparency and impact on civic integration.", ES: "Ser una organización de referencia en educación, libertad y solidaridad con los inmigrantes, reconocida por su transparencia e impacto en la integración cívica." },
  "whoWeAre.values": { EN: "Core Values", ES: "Valores Fundamentales" },
  "whoWeAre.valuesDesc": { EN: "Dignity, rule of law, transparency, solidarity, and non-violence guide everything we do.", ES: "Dignidad, estado de derecho, transparencia, solidaridad y no violencia guían todo lo que hacemos." },
  "whoWeAre.readMore": { EN: "Read our full mission and bylaws", ES: "Lee nuestra misión completa y estatutos" },

  // What We Do Section
  "whatWeDo.title": { EN: "What we do", ES: "Qué hacemos" },
  "whatWeDo.description": { EN: "Our programs protect, educate, and empower Cuban migrants across the United States.", ES: "Nuestros programas protegen, educan y empoderan a migrantes cubanos en Estados Unidos." },
  "whatWeDo.oeam.title": { EN: "Ethical and Anti-Fraud Migratory Observatory (OEAM)", ES: "Observatorio Ético y Antifraude Migratorio (OEAM)" },
  "whatWeDo.oeam.desc": { EN: "We receive and document complaints about fraud, abusive practices, or misconduct by notaries, lawyers, and others offering immigration services. We escalate verified cases to authorities.", ES: "Recibimos y documentamos quejas sobre fraude, prácticas abusivas o mala conducta de notarios, abogados y otros que ofrecen servicios migratorios. Escalamos casos verificados a las autoridades." },
  "whatWeDo.oeam.note": { EN: "Note: We do not provide individual legal representation.", ES: "Nota: No proporcionamos representación legal individual." },
  "whatWeDo.education.title": { EN: "Civic Education and CAA Awareness", ES: "Educación Cívica y Concientización sobre la CAA" },
  "whatWeDo.education.desc": { EN: "Workshops, online materials, and guides that explain rights and duties under U.S. law, the basics of the Cuban Adjustment Act, and how to avoid misinformation.", ES: "Talleres, materiales en línea y guías que explican derechos y deberes bajo la ley estadounidense, los fundamentos de la Ley de Ajuste Cubano y cómo evitar la desinformación." },
  "whatWeDo.community.title": { EN: "Community Support & Ambassadors Program", ES: "Apoyo Comunitario y Programa de Embajadores" },
  "whatWeDo.community.desc": { EN: "A network of community ambassadors in different cities and states that share verified information, detect patterns of abuse, and connect families with reliable resources.", ES: "Una red de embajadores comunitarios en diferentes ciudades y estados que comparten información verificada, detectan patrones de abuso y conectan familias con recursos confiables." },
  "whatWeDo.learnMore": { EN: "Learn more about our work", ES: "Conoce más sobre nuestro trabajo" },

  // Impact Stats
  "impact.title": { EN: "How your donation helps", ES: "Cómo ayuda tu donación" },
  "impact.description": { EN: "Every contribution strengthens our ability to protect and serve the Cuban community.", ES: "Cada contribución fortalece nuestra capacidad de proteger y servir a la comunidad cubana." },
  "impact.stat1": { EN: "Educational materials created and updated regularly", ES: "Materiales educativos creados y actualizados regularmente" },
  "impact.stat2": { EN: "Community complaints documented and monitored against fraud", ES: "Quejas comunitarias documentadas y monitoreadas contra el fraude" },
  "impact.stat3": { EN: "Ambassadors and volunteers supporting families in multiple states", ES: "Embajadores y voluntarios apoyando familias en múltiples estados" },
  "impact.stat4": { EN: "Reports and alerts issued to protect the community", ES: "Informes y alertas emitidos para proteger a la comunidad" },
  "impact.transparency": { EN: "See our transparency and reports", ES: "Ver nuestra transparencia e informes" },

  // Blog Section
  "blog.title": { EN: "Latest from our blog", ES: "Lo último de nuestro blog" },
  "blog.description": { EN: "News, guides, and stories from our community.", ES: "Noticias, guías e historias de nuestra comunidad." },
  "blog.visitBlog": { EN: "Visit the Blog", ES: "Visitar el Blog" },

  // Public Documents Section
  "docs.title": { EN: "Public Documents", ES: "Documentos Públicos" },
  "docs.description": { EN: "Access our reports and resources available to the public.", ES: "Accede a nuestros informes, reportes y recursos disponibles para la comunidad." },
  "docs.viewAll": { EN: "View all resources", ES: "Ver todos los recursos" },
  "docs.report2025.tag": { EN: "Financial & Operational Report", ES: "Informe Financiero y Operativo" },
  "docs.report2025.title": { EN: "Financial & Operational Report - March 2026", ES: "Informe Financiero y Operativo - Marzo 2026" },
  "docs.report2025.desc": { EN: "Complete financial transparency report detailing our impact, operational efficiency, community assistance programs, and institutional achievements for March 2026.", ES: "Informe completo de transparencia financiera detallando nuestro impacto, eficiencia operativa, programas de asistencia comunitaria y logros institucionales de marzo 2026." },
  "docs.download": { EN: "Download PDF", ES: "Descargar PDF" },
  "blog.readMore": { EN: "Read more", ES: "Leer más" },
  "blog.backToBlog": { EN: "Back to blog", ES: "Volver al blog" },
  "blog.postNotFound": { EN: "Post not found", ES: "Publicación no encontrada" },
  "blog.disclaimer": { EN: "This article is for educational and informational purposes only. It does not constitute legal advice. For advice about your specific situation, please consult a licensed attorney.", ES: "Este artículo es solo para fines educativos e informativos. No constituye asesoramiento legal. Para consejos sobre su situación específica, consulte a un abogado licenciado." },

  // Blog Posts
  "blog.post1.title": { EN: "What is the Cuban Adjustment Act (CAA) and how does it work?", ES: "¿Qué es la Ley de Ajuste Cubano (CAA) y cómo funciona?" },
  "blog.post1.excerpt": { EN: "Learn the basics of this important law that has helped Cuban migrants find stability in the United States for decades.", ES: "Conoce los fundamentos de esta importante ley que ha ayudado a migrantes cubanos a encontrar estabilidad en Estados Unidos durante décadas." },
  "blog.post1.tag": { EN: "CAA basics", ES: "Fundamentos CAA" },
  "blog.post2.title": { EN: "How to avoid fraud in immigration services: 5 warning signs", ES: "Cómo evitar el fraude en servicios migratorios: 5 señales de advertencia" },
  "blog.post2.excerpt": { EN: "Protect yourself and your family from scams and abusive practices when seeking immigration help.", ES: "Protégete a ti y a tu familia de estafas y prácticas abusivas al buscar ayuda migratoria." },
  "blog.post2.tag": { EN: "Fraud prevention", ES: "Prevención de fraude" },
  "blog.post3.title": { EN: "Community ambassadors: Cuban voices protecting Cuban families", ES: "Embajadores comunitarios: Voces cubanas protegiendo familias cubanas" },
  "blog.post3.excerpt": { EN: "Meet the volunteers across the United States who share verified information and support our community.", ES: "Conoce a los voluntarios en Estados Unidos que comparten información verificada y apoyan a nuestra comunidad." },
  "blog.post3.tag": { EN: "Community stories", ES: "Historias comunitarias" },

  // Join / Inscription Section
  "join.title": { EN: "Join Defenders of the CAA and Freedom", ES: "Únete a Defensores de la CAA y la Libertad" },
  "join.description": { EN: "Be part of a community committed to defending the rights and freedom of Cubans. Register as a member and contribute your time, knowledge, or support to create real impact.", ES: "Forma parte de una comunidad comprometida con la defensa de los derechos y la libertad de los cubanos. Regístrate como miembro y contribuye con tu tiempo, conocimiento o apoyo para generar un impacto real en nuestra comunidad." },
  "join.button": { EN: "Create or update your profile", ES: "Crea o actualiza tu perfil" },

  // CTA Strip
  "cta.title": { EN: "Cuban migrants deserve dignity, truth, and the protection of the law.", ES: "Los migrantes cubanos merecen dignidad, verdad y la protección de la ley." },
  "cta.description": { EN: "Join us in defending the Cuban Adjustment Act and protecting our community from fraud and abuse.", ES: "Únete a nosotros en la defensa de la Ley de Ajuste Cubano y protegiendo a nuestra comunidad del fraude y abuso." },
  "cta.takeAction": { EN: "Take action", ES: "Tomar acción" },
  "cta.becomeMember": { EN: "Become a member or volunteer", ES: "Hazte miembro o voluntario" },

  // About Page
  "about.title": { EN: "About Us", ES: "Nosotros" },
  "about.heroDesc": { EN: "Defenders of the CAA and Freedom, Inc. is a non-partisan, community-based organization dedicated to protecting the rights of Cuban Migrants and the Defense of the Humanitarian Principles of the Cuban Adjustment Act and the Freedom of Cuba.", ES: "Defensores de la CAA y la Libertad, Inc. es una organización comunitaria no partidista dedicada a proteger los derechos de los migrantes cubanos y defender los principios humanitarios de la Ley de Ajuste Cubano y la libertad de Cuba." },
  "about.whoWeAre.title": { EN: "Who we are", ES: "Quiénes somos" },
  "about.whoWeAre.p1": { EN: "We are a <strong>non-profit organization</strong> created under <strong>Chapter 617 of the Florida Statutes</strong>, recognized as a <strong>501(c)(3) tax-exempt organization</strong>.", ES: "Somos una <strong>organización sin fines de lucro</strong> creada bajo el <strong>Capítulo 617 de los Estatutos de Florida</strong>, reconocida como <strong>organización exenta de impuestos 501(c)(3)</strong>." },
  "about.whoWeAre.p2": { EN: "Our headquarters are in Florida, with 9 active chapters in: Tampa, Brandon, Riverview, Hayalia, Orlando, Dallas, Corpus Christi, Houston, and Austin.", ES: "Nuestra sede está en Florida, con 9 capítulos activos en: Tampa, Brandon, Riverview, Hayalia, Orlando, Dallas, Corpus Christi, Houston y Austin." },
  "about.whoWeAre.p3": { EN: "All resources are used exclusively for institutional purposes. Board members and directors do not receive personal financial benefits from the organization.", ES: "Todos los recursos se usan exclusivamente para propósitos institucionales. Los miembros de la junta y directores no reciben beneficios financieros personales de la organización." },
  "about.legalStatus": { EN: "Legal Status", ES: "Estatus Legal" },
  "about.floridaNonProfit": { EN: "Florida Non-Profit", ES: "Sin Fines de Lucro en Florida" },
  "about.legal1": { EN: "Organized under Chapter 617, Florida Statutes", ES: "Organizada bajo el Capítulo 617, Estatutos de Florida" },
  "about.legal2": { EN: "Eligible for 501(c)(3) tax-exempt status", ES: "Elegible para estatus de exención de impuestos 501(c)(3)" },
  "about.legal3": { EN: "Non-partisan and politically independent", ES: "No partidista y políticamente independiente" },
  "about.legal4": { EN: "Community-governed with volunteer leadership", ES: "Gobernada por la comunidad con liderazgo voluntario" },
  "about.mission.title": { EN: "Our Mission", ES: "Nuestra Misión" },
  "about.mission.desc": { EN: "To promote social justice and human dignity for immigrants, especially Cubans, through civic education, community assistance, and social integration. We strengthen participation and positive contribution of Cuban and Latin American migrants to U.S. society.", ES: "Promover la justicia social y la dignidad humana para los inmigrantes, especialmente los cubanos, a través de la educación cívica, asistencia comunitaria e integración social. Fortalecemos la participación y contribución positiva de los migrantes cubanos y latinoamericanos a la sociedad estadounidense." },
  "about.vision.title": { EN: "Our Vision", ES: "Nuestra Visión" },
  "about.vision.desc": { EN: "To be a reference organization in education, freedom, and solidarity with immigrants, recognized for transparency and impact on civic and cultural integration of Cubans and Latinos in the United States.", ES: "Ser una organización de referencia en educación, libertad y solidaridad con los inmigrantes, reconocida por su transparencia e impacto en la integración cívica y cultural de cubanos y latinos en Estados Unidos." },
  "about.objectives.title": { EN: "Core Objectives", ES: "Objetivos Principales" },
  "about.obj.civicEd": { EN: "Civic Education", ES: "Educación Cívica" },
  "about.obj.civicEdDesc": { EN: "Provide civic and community education for Cuban and Latin American immigrants.", ES: "Proporcionar educación cívica y comunitaria para inmigrantes cubanos y latinoamericanos." },
  "about.obj.support": { EN: "Support Programs", ES: "Programas de Apoyo" },
  "about.obj.supportDesc": { EN: "Develop support and solidarity programs that foster integration, respect, and democratic values.", ES: "Desarrollar programas de apoyo y solidaridad que fomenten la integración, el respeto y los valores democráticos." },
  "about.obj.caaDefense": { EN: "CAA Defense", ES: "Defensa de la CAA" },
  "about.obj.caaDefenseDesc": { EN: "Defend and preserve the humanitarian principles of the Cuban Adjustment Act as a pathway for family integration.", ES: "Defender y preservar los principios humanitarios de la Ley de Ajuste Cubano como vía para la integración familiar." },
  "about.obj.rootCauses": { EN: "Root Causes", ES: "Causas Raíz" },
  "about.obj.rootCausesDesc": { EN: "Highlight the consequences of communism and dictatorships as root causes of forced migration.", ES: "Destacar las consecuencias del comunismo y las dictaduras como causas raíz de la migración forzada." },
  "about.obj.dignity": { EN: "Dignity Campaigns", ES: "Campañas de Dignidad" },
  "about.obj.dignityDesc": { EN: "Run campaigns that dignify the image of migrants and highlight their social, economic, and cultural contributions.", ES: "Ejecutar campañas que dignifiquen la imagen de los migrantes y destaquen sus contribuciones sociales, económicas y culturales." },
  "about.obj.fraudPrev": { EN: "Fraud Prevention", ES: "Prevención de Fraude" },
  "about.obj.fraudPrevDesc": { EN: "Monitor and report abusive practices targeting Cuban migrants in immigration services.", ES: "Monitorear y reportar prácticas abusivas dirigidas a migrantes cubanos en servicios migratorios." },
  "about.values.title": { EN: "Core Values", ES: "Valores Fundamentales" },
  "about.value.dignity": { EN: "Dignity", ES: "Dignidad" },
  "about.value.dignityDesc": { EN: "Every person deserves respect and fair treatment.", ES: "Toda persona merece respeto y trato justo." },
  "about.value.law": { EN: "Rule of Law", ES: "Estado de Derecho" },
  "about.value.lawDesc": { EN: "We uphold legal processes and due rights.", ES: "Defendemos los procesos legales y los derechos debidos." },
  "about.value.transparency": { EN: "Transparency", ES: "Transparencia" },
  "about.value.transparencyDesc": { EN: "Open governance and accountable operations.", ES: "Gobernanza abierta y operaciones responsables." },
  "about.value.solidarity": { EN: "Solidarity", ES: "Solidaridad" },
  "about.value.solidarityDesc": { EN: "Community support and mutual assistance.", ES: "Apoyo comunitario y asistencia mutua." },
  "about.value.nonviolence": { EN: "Non-violence", ES: "No Violencia" },
  "about.value.nonviolenceDesc": { EN: "Peaceful advocacy and education.", ES: "Abogacía pacífica y educación." },
  "about.governance.title": { EN: "Governance", ES: "Gobernanza" },
  "about.governance.desc": { EN: "Our organization is governed democratically with full transparency.", ES: "Nuestra organización es gobernada democráticamente con total transparencia." },
  "about.governance.assembly": { EN: "General Assembly", ES: "Asamblea General" },
  "about.governance.assemblyDesc": { EN: "The supreme decision-making body of the organization. Meets at least once per year to approve budgets, elect directors, and set strategic direction.", ES: "El órgano supremo de toma de decisiones de la organización. Se reúne al menos una vez al año para aprobar presupuestos, elegir directores y establecer la dirección estratégica." },
  "about.governance.board": { EN: "Board of Directors", ES: "Junta Directiva" },
  "about.governance.boardDesc": { EN: "Seven volunteer members responsible for administration, budgeting, accountability, and transparency:", ES: "Siete miembros voluntarios responsables de la administración, presupuesto, rendición de cuentas y transparencia:" },
  "about.governance.president": { EN: "President", ES: "Presidente" },
  "about.governance.vp": { EN: "Vice President", ES: "Vicepresidente" },
  "about.governance.secretary": { EN: "Secretary-Treasurer", ES: "Secretario-Tesorero" },
  "about.governance.pr": { EN: "Director of Public Relations", ES: "Director de Relaciones Públicas" },
  "about.governance.vocal1": { EN: "Board Member (Vocal) 1", ES: "Vocal 1" },
  "about.governance.vocal2": { EN: "Board Member (Vocal) 2", ES: "Vocal 2" },
  "about.governance.vocal3": { EN: "Board Member (Vocal) 3", ES: "Vocal 3" },
  "about.chapters.title": { EN: "Territorial Chapters", ES: "Capítulos Territoriales" },
  "about.chapters.desc": { EN: "Local chapters can be created when there are enough active members in a city or state. Local boards help execute national programs, promote membership, and report regularly. Chapters do not have independent legal personality but operate under the national organization's governance.", ES: "Los capítulos locales pueden crearse cuando hay suficientes miembros activos en una ciudad o estado. Las juntas locales ayudan a ejecutar programas nacionales, promover membresía e informar regularmente. Los capítulos no tienen personalidad jurídica independiente pero operan bajo la gobernanza de la organización nacional." },
  "about.cta.bylaws": { EN: "Read our bylaws (PDF)", ES: "Lee nuestros estatutos (PDF)" },
  "about.cta.join": { EN: "Join as a member", ES: "Únete como miembro" },

  // Partner Companies (home page)
  "partners.eyebrow": { EN: "Our Partners", ES: "Nuestros Aliados" },
  "partners.title": { EN: "Companies that support us", ES: "Compañías que nos apoyan" },
  "partners.desc": { EN: "Organizations that collaborate with us to amplify our mission and serve the Cuban community.", ES: "Organizaciones que colaboran con nosotros para amplificar nuestra misión y servir a la comunidad cubana." },

  // Team Sections
  "about.team.eyebrow": { EN: "Our Team", ES: "Nuestro Equipo" },
  "about.team.board.title": { EN: "Board of Directors", ES: "Junta Directiva" },
  "about.team.board.desc": { EN: "Volunteer leaders committed to transparency, accountability, and the organization's strategic direction.", ES: "Líderes voluntarios comprometidos con la transparencia, la rendición de cuentas y la dirección estratégica de la organización." },
  "about.team.ambassadors.title": { EN: "Ambassadors", ES: "Embajadores" },
  "about.team.ambassadors.desc": { EN: "Our community representatives across the United States, extending our reach and supporting Cuban migrants locally.", ES: "Nuestros representantes comunitarios en Estados Unidos, extendiendo nuestro alcance y apoyando a los migrantes cubanos localmente." },
  "about.team.companies.title": { EN: "Partner Companies", ES: "Compañías Aliadas" },
  "about.team.companies.desc": { EN: "Organizations that collaborate with us to amplify our mission and serve the community.", ES: "Organizaciones que colaboran con nosotros para amplificar nuestra misión y servir a la comunidad." },

  // Our Work Page
  "ourWork.title": { EN: "Our Work", ES: "Nuestro Trabajo" },
  "ourWork.heroDesc": { EN: "Through education, monitoring, and community support, we protect Cuban migrants and defend the humanitarian principles of the Cuban Adjustment Act.", ES: "A través de la educación, monitoreo y apoyo comunitario, protegemos a los migrantes cubanos y defendemos los principios humanitarios de la Ley de Ajuste Cubano." },
  "ourWork.oeam.title": { EN: "Ethical and Anti-Fraud Migratory Observatory", ES: "Observatorio Ético y Antifraude Migratorio" },
  "ourWork.oeam.acronym": { EN: "(OEAM)", ES: "(OEAM)" },
  "ourWork.oeam.intro": { EN: "The OEAM is a permanent program to <strong>receive, document, analyze, and help affected parties channel complaints</strong> about fraudulent, abusive, or deceptive practices by:", ES: "El OEAM es un programa permanente para <strong>recibir, documentar, analizar y ayudar al afectado a canalizar quejas</strong> sobre prácticas fraudulentas, abusivas o engañosas por parte de:" },
  "ourWork.oeam.notaries": { EN: "Notaries", ES: "Notarios" },
  "ourWork.oeam.lawyers": { EN: "Lawyers", ES: "Abogados" },
  "ourWork.oeam.paralegals": { EN: "Paralegals", ES: "Paralegales" },
  "ourWork.oeam.docPrep": { EN: "Document preparers", ES: "Preparadores de documentos" },
  "ourWork.oeam.anyone": { EN: "Any person offering legal or migration services", ES: "Cualquier persona que ofrezca servicios legales o migratorios" },
  "ourWork.oeam.doesTitle": { EN: "What the OEAM does", ES: "Qué hace el OEAM" },
  "ourWork.oeam.does1": { EN: "Receives complaints from community members", ES: "Recibe quejas de miembros de la comunidad" },
  "ourWork.oeam.does2": { EN: "Verifies credibility and basic evidence", ES: "Verifica credibilidad y evidencia básica" },
  "ourWork.oeam.does3": { EN: "Opens internal case files with codes (e.g., OEAM-FL-2025-001)", ES: "Abre expedientes internos con códigos (ej., OEAM-FL-2025-001)" },
  "ourWork.oeam.does4": { EN: "Detects patterns when multiple complaints target the same professional", ES: "Detecta patrones cuando múltiples quejas apuntan al mismo profesional" },
  "ourWork.oeam.does5": { EN: "Helps affected parties submit formal institutional complaints to the authority", ES: "Ayuda a los afectados a presentar quejas institucionales formales a la autoridad" },
  "ourWork.oeam.does6": { EN: "Issues public alerts and educational campaigns", ES: "Emite alertas públicas y campañas educativas" },
  "ourWork.oeam.does7": { EN: "Protects confidentiality of complainants", ES: "Protege la confidencialidad de los denunciantes" },
  "ourWork.oeam.doesNotTitle": { EN: "What the OEAM does NOT do", ES: "Qué NO hace el OEAM" },
  "ourWork.oeam.doesNot1": { EN: "Provide individual legal representation", ES: "Proporcionar representación legal individual" },
  "ourWork.oeam.doesNot2": { EN: "Replace attorneys or legal counsel", ES: "Reemplazar abogados o asesorías legales" },
  "ourWork.oeam.doesNot3": { EN: "Litigate cases on behalf of individuals", ES: "Litigar casos en nombre de individuos" },
  "ourWork.oeam.doesNot4": { EN: "Give legal advice for specific situations", ES: "Dar asesoría legal para situaciones específicas" },
  "ourWork.oeam.escalate": { EN: "Where we escalate verified cases:", ES: "Dónde escalamos casos verificados:" },
  "ourWork.oeam.escalate1": { EN: "State Bar associations", ES: "Colegios de Abogados estatales" },
  "ourWork.oeam.escalate2": { EN: "State departments regulating notaries", ES: "Departamentos estatales que regulan notarios" },
  "ourWork.oeam.escalate3": { EN: "Consumer protection departments", ES: "Departamentos de protección al consumidor" },
  "ourWork.oeam.escalate4": { EN: "State Attorneys General", ES: "Fiscales Generales del Estado" },
  "ourWork.education.title": { EN: "Education & Civic Awareness", ES: "Educación y Conciencia Cívica" },
  "ourWork.education.desc": { EN: "We provide workshops, online materials, and guides that help our community understand their rights and responsibilities.", ES: "Proporcionamos talleres, materiales en línea y guías que ayudan a nuestra comunidad a entender sus derechos y responsabilidades." },
  "ourWork.education.rights": { EN: "Rights & Responsibilities", ES: "Derechos y Responsabilidades" },
  "ourWork.education.rightsDesc": { EN: "Understanding immigrant rights and duties under U.S. law.", ES: "Entendiendo los derechos y deberes de los inmigrantes bajo la ley estadounidense." },
  "ourWork.education.caa": { EN: "CAA Basics", ES: "Fundamentos de la CAA" },
  "ourWork.education.caaDesc": { EN: "The fundamentals of the Cuban Adjustment Act and related processes.", ES: "Los fundamentos de la Ley de Ajuste Cubano y procesos relacionados." },
  "ourWork.education.fraud": { EN: "Fraud Prevention", ES: "Prevención de Fraude" },
  "ourWork.education.fraudDesc": { EN: "How to identify and avoid scams and misinformation.", ES: "Cómo identificar y evitar estafas y desinformación." },
  "ourWork.education.democratic": { EN: "Democratic Values", ES: "Valores Democráticos" },
  "ourWork.education.democraticDesc": { EN: "Human rights, civic participation, and the history of Cuban exile.", ES: "Derechos humanos, participación cívica y la historia del exilio cubano." },
  "ourWork.community.title": { EN: "Community Support & Ambassadors Program", ES: "Apoyo Comunitario y Programa de Embajadores" },
  "ourWork.community.desc": { EN: "Our network of community ambassadors across the United States serves as trusted voices for Cuban families.", ES: "Nuestra red de embajadores comunitarios en Estados Unidos sirve como voces confiables para las familias cubanas." },
  "ourWork.community.whatDo": { EN: "What ambassadors do", ES: "Qué hacen los embajadores" },
  "ourWork.community.do1": { EN: "Share verified information with their local communities", ES: "Comparten información verificada con sus comunidades locales" },
  "ourWork.community.do2": { EN: "Help families understand trustworthy resources", ES: "Ayudan a las familias a entender recursos confiables" },
  "ourWork.community.do3": { EN: "Collect non-confidential data on local problems", ES: "Recopilan datos no confidenciales sobre problemas locales" },
  "ourWork.community.do4": { EN: "Support events, forums, and outreach campaigns", ES: "Apoyan eventos, foros y campañas de alcance" },
  "ourWork.community.become": { EN: "Become an Ambassador", ES: "Conviértete en Embajador" },
  "ourWork.community.becomeDesc": { EN: "Are you passionate about helping Cuban migrants in your city? Join our network of community ambassadors.", ES: "¿Te apasiona ayudar a migrantes cubanos en tu ciudad? Únete a nuestra red de embajadores comunitarios." },
  "ourWork.community.apply": { EN: "Apply to become an ambassador", ES: "Solicita ser embajador" },
  "ourWork.transparency.title": { EN: "Transparency & Reporting", ES: "Transparencia e Informes" },
  "ourWork.transparency.desc": { EN: "We publish regular reports to maintain full accountability with our community and donors.", ES: "Publicamos informes regulares para mantener total responsabilidad con nuestra comunidad y donantes." },
  "ourWork.transparency.stats": { EN: "Complaint Statistics", ES: "Estadísticas de Quejas" },
  "ourWork.transparency.resolved": { EN: "Resolved Cases", ES: "Casos Resueltos" },
  "ourWork.transparency.materials": { EN: "Educational Materials", ES: "Materiales Educativos" },
  "ourWork.transparency.financial": { EN: "Financial Reports", ES: "Informes Financieros" },
  "ourWork.transparency.view": { EN: "View our reports and resources", ES: "Ver nuestros informes y recursos" },
  "ourWork.cta.title": { EN: "Support our work", ES: "Apoya nuestro trabajo" },
  "ourWork.cta.desc": { EN: "Your donation helps us protect Cuban migrants, fight fraud, and defend the Cuban Adjustment Act.", ES: "Tu donación nos ayuda a proteger a migrantes cubanos, combatir el fraude y defender la Ley de Ajuste Cubano." },
  "ourWork.cta.donate": { EN: "Donate now", ES: "Donar ahora" },
  "ourWork.cta.volunteer": { EN: "Join as a volunteer", ES: "Únete como voluntario" },

  // Blog Page
  "blog.heroTitle": { EN: "Blog & News", ES: "Blog y Noticias" },
  "blog.heroDesc": { EN: "News, guides, and stories from our community. Stay informed about the Cuban Adjustment Act, fraud prevention, and community updates.", ES: "Noticias, guías e historias de nuestra comunidad. Mantente informado sobre la Ley de Ajuste Cubano, prevención de fraude y actualizaciones comunitarias." },
  "blog.tagAll": { EN: "All", ES: "Todos" },
  "blog.tagCaaBasics": { EN: "CAA basics", ES: "Fundamentos CAA" },
  "blog.tagFraudPrevention": { EN: "Fraud prevention", ES: "Prevención de fraude" },
  "blog.tagPolicy": { EN: "Policy and context", ES: "Política y contexto" },
  "blog.tagCommunity": { EN: "Community stories", ES: "Historias comunitarias" },
  "blog.tagObservatory": { EN: "Observatory reports", ES: "Informes del observatorio" },

  // Get Involved Page
  "getInvolved.title": { EN: "Get Involved", ES: "Participa" },
  "getInvolved.heroDesc": { EN: "Join our community of Cuban migrants, professionals, and allies working together to protect rights and promote dignity.", ES: "Únete a nuestra comunidad de migrantes cubanos, profesionales y aliados trabajando juntos para proteger derechos y promover la dignidad." },
  "getInvolved.member.title": { EN: "Become a Member", ES: "Hazte Miembro" },
  "getInvolved.member.desc": { EN: "Members are adults who share our mission and want to actively participate in defending the rights of Cuban migrants. Membership is open to Cuban nationals, people of Cuban origin, and allies.", ES: "Los miembros son adultos que comparten nuestra misión y quieren participar activamente en la defensa de los derechos de los migrantes cubanos. La membresía está abierta a nacionales cubanos, personas de origen cubano y aliados." },
  "getInvolved.member.rights": { EN: "Member rights include:", ES: "Los derechos de los miembros incluyen:" },
  "getInvolved.member.benefit1": { EN: "Voice and vote in General Assembly meetings", ES: "Voz y voto en las reuniones de la Asamblea General" },
  "getInvolved.member.benefit2": { EN: "Participate in commissions and working groups", ES: "Participar en comisiones y grupos de trabajo" },
  "getInvolved.member.benefit3": { EN: "Access to member-only resources and updates", ES: "Acceso a recursos y actualizaciones exclusivas para miembros" },
  "getInvolved.member.benefit4": { EN: "Opportunity to serve on the Board of Directors", ES: "Oportunidad de servir en la Junta Directiva" },
  "getInvolved.member.benefit5": { EN: "Connect with other community members nationwide", ES: "Conectar con otros miembros de la comunidad en todo el país" },
  "getInvolved.form.title": { EN: "Apply to become a member", ES: "Solicita hacerte miembro" },
  "getInvolved.form.name": { EN: "Full name", ES: "Nombre completo" },
  "getInvolved.form.email": { EN: "Email", ES: "Correo electrónico" },
  "getInvolved.form.city": { EN: "City", ES: "Ciudad" },
  "getInvolved.form.state": { EN: "State", ES: "Estado" },
  "getInvolved.form.interest": { EN: "How do you want to help?", ES: "¿Cómo quieres ayudar?" },
  "getInvolved.form.selectOption": { EN: "Select an option", ES: "Selecciona una opción" },
  "getInvolved.form.generalMembership": { EN: "General membership", ES: "Membresía general" },
  "getInvolved.form.ambassador": { EN: "Community ambassador", ES: "Embajador comunitario" },
  "getInvolved.form.volunteer": { EN: "Volunteer", ES: "Voluntario" },
  "getInvolved.form.professional": { EN: "Professional support", ES: "Apoyo profesional" },
  "getInvolved.form.aboutYou": { EN: "Tell us about yourself (optional)", ES: "Cuéntanos sobre ti (opcional)" },
  "getInvolved.form.placeholder": { EN: "Your background, skills, or why you want to join...", ES: "Tu experiencia, habilidades o por qué quieres unirte..." },
  "getInvolved.form.submit": { EN: "Submit application", ES: "Enviar solicitud" },
  "getInvolved.volunteer.title": { EN: "Volunteer Opportunities", ES: "Oportunidades de Voluntariado" },
  "getInvolved.volunteer.desc": { EN: "Use your skills to make a difference. We have various roles for people with different talents and availability.", ES: "Usa tus habilidades para hacer la diferencia. Tenemos varios roles para personas con diferentes talentos y disponibilidad." },
  "getInvolved.volunteer.ambassador": { EN: "Ambassador", ES: "Embajador" },
  "getInvolved.volunteer.ambassadorDesc": { EN: "Represent us in your local community", ES: "Represéntanos en tu comunidad local" },
  "getInvolved.volunteer.translator": { EN: "Translator", ES: "Traductor" },
  "getInvolved.volunteer.translatorDesc": { EN: "Help translate materials to Spanish", ES: "Ayuda a traducir materiales al español" },
  "getInvolved.volunteer.designer": { EN: "Designer", ES: "Diseñador" },
  "getInvolved.volunteer.designerDesc": { EN: "Create visual content and materials", ES: "Crea contenido visual y materiales" },
  "getInvolved.volunteer.contentCreator": { EN: "Content Creator", ES: "Creador de Contenido" },
  "getInvolved.volunteer.contentCreatorDesc": { EN: "Write articles and social media content", ES: "Escribe artículos y contenido para redes sociales" },
  "getInvolved.volunteer.eventOrganizer": { EN: "Event Organizer", ES: "Organizador de Eventos" },
  "getInvolved.volunteer.eventOrganizerDesc": { EN: "Help plan and run community events", ES: "Ayuda a planificar y organizar eventos comunitarios" },
  "getInvolved.donate.title": { EN: "Support with a donation", ES: "Apoya con una donación" },
  "getInvolved.donate.desc": { EN: "Can't volunteer your time? Your financial support helps us continue protecting Cuban migrants, fighting fraud, and providing education to our community.", ES: "¿No puedes donar tu tiempo? Tu apoyo financiero nos ayuda a continuar protegiendo a migrantes cubanos, combatiendo el fraude y proporcionando educación a nuestra comunidad." },
  "getInvolved.donate.button": { EN: "Donate now", ES: "Donar ahora" },
  
  // Toast messages
  "toast.applicationSubmitted": { EN: "Application submitted!", ES: "¡Solicitud enviada!" },
  "toast.applicationDesc": { EN: "Thank you for your interest. We will contact you soon.", ES: "Gracias por tu interés. Te contactaremos pronto." },

  // Resources Page
  "resources.title": { EN: "Resources", ES: "Recursos" },
  "resources.heroDesc": { EN: "Guides, checklists, and frequently asked questions to help you understand your rights and navigate the immigration process.", ES: "Guías, listas de verificación y preguntas frecuentes para ayudarte a entender tus derechos y navegar el proceso migratorio." },
  "resources.disclaimer": { EN: "This website does not provide legal advice. We offer information and community support only. For legal advice about your specific situation, please consult a licensed attorney.", ES: "Este sitio web no proporciona asesoramiento legal. Ofrecemos solo información y apoyo comunitario. Para asesoramiento legal sobre tu situación específica, consulta a un abogado licenciado." },
  "resources.guidesTitle": { EN: "Guides & Resources", ES: "Guías y Recursos" },
  "resources.guide1.title": { EN: "Guide: Understanding the Cuban Adjustment Act", ES: "Guía: Entendiendo la Ley de Ajuste Cubano" },
  "resources.guide1.desc": { EN: "A comprehensive guide explaining the CAA, eligibility requirements, and the application process.", ES: "Una guía completa que explica la CAA, requisitos de elegibilidad y el proceso de solicitud." },
  "resources.guide2.title": { EN: "Checklist: Documents to keep for your case", ES: "Lista de verificación: Documentos para tu caso" },
  "resources.guide2.desc": { EN: "Essential documents you should gather and maintain for your immigration case.", ES: "Documentos esenciales que debes reunir y mantener para tu caso migratorio." },
  "resources.guide3.title": { EN: "Directory: Legal aid and trusted nonprofit organizations", ES: "Directorio: Ayuda legal y organizaciones sin fines de lucro confiables" },
  "resources.guide3.desc": { EN: "A curated list of verified legal aid organizations that serve Cuban migrants.", ES: "Una lista curada de organizaciones de ayuda legal verificadas que sirven a migrantes cubanos." },
  "resources.downloadPdf": { EN: "Download PDF", ES: "Descargar PDF" },
  "resources.viewDirectory": { EN: "View Directory", ES: "Ver Directorio" },
  "resources.faq.title": { EN: "Frequently Asked Questions", ES: "Preguntas Frecuentes" },
  "resources.faq.desc": { EN: "Common questions about the CAA, our organization, and immigration processes.", ES: "Preguntas comunes sobre la CAA, nuestra organización y procesos migratorios." },
  "resources.faq.q1": { EN: "What is the Cuban Adjustment Act (CAA)?", ES: "¿Qué es la Ley de Ajuste Cubano (CAA)?" },
  "resources.faq.a1": { EN: "The Cuban Adjustment Act is a 1966 federal law that allows Cuban nationals who have been physically present in the United States for at least one year to apply for permanent resident status (green card). It is a unique pathway that recognizes the special circumstances of Cuban migrants.", ES: "La Ley de Ajuste Cubano es una ley federal de 1966 que permite a los nacionales cubanos que han estado físicamente presentes en Estados Unidos por al menos un año solicitar el estatus de residente permanente (green card). Es una vía única que reconoce las circunstancias especiales de los migrantes cubanos." },
  "resources.faq.q2": { EN: "Who is eligible to apply under the CAA?", ES: "¿Quién es elegible para aplicar bajo la CAA?" },
  "resources.faq.a2": { EN: "To be eligible, you must be a native or citizen of Cuba, have been inspected and admitted or paroled into the United States, have been physically present for at least one year, and be admissible as an immigrant. Each case is unique, so we recommend consulting with a licensed attorney.", ES: "Para ser elegible, debes ser nativo o ciudadano de Cuba, haber sido inspeccionado y admitido o en parole en Estados Unidos, haber estado físicamente presente por al menos un año, y ser admisible como inmigrante. Cada caso es único, por lo que recomendamos consultar con un abogado licenciado." },
  "resources.faq.q3": { EN: "How long does the CAA application process take?", ES: "¿Cuánto tiempo toma el proceso de aplicación de la CAA?" },
  "resources.faq.a3": { EN: "Processing times vary depending on USCIS workload and individual case circumstances. Generally, it can take several months to over a year. Check the USCIS website for current processing times and consider consulting an attorney for your specific situation.", ES: "Los tiempos de procesamiento varían dependiendo de la carga de trabajo de USCIS y las circunstancias individuales del caso. Generalmente, puede tomar varios meses a más de un año. Consulta el sitio web de USCIS para tiempos de procesamiento actuales y considera consultar a un abogado para tu situación específica." },
  "resources.faq.q4": { EN: "Can I apply for my family members under the CAA?", ES: "¿Puedo aplicar para mis familiares bajo la CAA?" },
  "resources.faq.a4": { EN: "Spouses and unmarried children under 21 who are also Cuban nationals may be included in your application or file their own applications. Family reunification is one of the humanitarian goals of the CAA.", ES: "Cónyuges e hijos solteros menores de 21 años que también son nacionales cubanos pueden ser incluidos en tu solicitud o presentar sus propias solicitudes. La reunificación familiar es uno de los objetivos humanitarios de la CAA." },
  "resources.faq.q5": { EN: "What should I do if I suspect immigration fraud?", ES: "¿Qué debo hacer si sospecho de fraude migratorio?" },
  "resources.faq.a5": { EN: "If you believe you have been a victim of fraud by a notary, lawyer, paralegal, or any person offering immigration services, you can report it to our Ethical and Anti-Fraud Migratory Observatory (OEAM). We document these cases and escalate them to the appropriate authorities.", ES: "Si crees que has sido víctima de fraude por un notario, abogado, paralegal o cualquier persona que ofrezca servicios migratorios, puedes reportarlo a nuestro Observatorio Ético y Antifraude Migratorio (OEAM). Documentamos estos casos y los escalamos a las autoridades correspondientes." },
  "resources.faq.q6": { EN: "Does your organization provide legal advice?", ES: "¿Su organización proporciona asesoramiento legal?" },
  "resources.faq.a6": { EN: "No, Defenders of the CAA and Freedom, Inc. does not provide legal advice or representation. We offer educational information, community support, and resources. For legal advice about your specific situation, please consult a licensed immigration attorney.", ES: "No, Defensores de la CAA y la Libertad, Inc. no proporciona asesoramiento legal ni representación. Ofrecemos información educativa, apoyo comunitario y recursos. Para asesoramiento legal sobre tu situación específica, consulta a un abogado de inmigración licenciado." },
  "resources.faq.q7": { EN: "How can I become a member or volunteer?", ES: "¿Cómo puedo hacerme miembro o voluntario?" },
  "resources.faq.a7": { EN: "You can apply to become a member or volunteer through our Get Involved page. We welcome adults who share our mission and want to contribute to protecting the Cuban community.", ES: "Puedes solicitar hacerte miembro o voluntario a través de nuestra página Participa. Damos la bienvenida a adultos que comparten nuestra misión y quieren contribuir a proteger a la comunidad cubana." },
  "resources.faq.q8": { EN: "What is Cuba's designation as a State Sponsor of Terrorism?", ES: "¿Qué es la designación de Cuba como Estado Patrocinador del Terrorismo?" },
  "resources.faq.a8": { EN: "Cuba is currently designated by the United States as a State Sponsor of Terrorism. This designation reflects concerns about human rights and security. Many Cubans are fleeing repression, which is why the CAA remains an important humanitarian pathway.", ES: "Cuba está actualmente designada por Estados Unidos como Estado Patrocinador del Terrorismo. Esta designación refleja preocupaciones sobre derechos humanos y seguridad. Muchos cubanos huyen de la represión, por lo que la CAA sigue siendo una vía humanitaria importante." },
  "resources.moreQuestions": { EN: "Have more questions?", ES: "¿Tienes más preguntas?" },
  "resources.moreQuestionsDesc": { EN: "Contact us or visit our blog for more educational content about the Cuban Adjustment Act and immigrant rights.", ES: "Contáctanos o visita nuestro blog para más contenido educativo sobre la Ley de Ajuste Cubano y los derechos de los inmigrantes." },
  "resources.contactUs": { EN: "Contact us", ES: "Contáctanos" },
  "resources.visitBlog": { EN: "Visit our blog", ES: "Visita nuestro blog" },

  // Contact Page
  "contact.title": { EN: "Contact Us", ES: "Contáctanos" },
  "contact.heroDesc": { EN: "Have questions, want to report fraud, or interested in getting involved? We're here to help.", ES: "¿Tienes preguntas, quieres reportar fraude o te interesa participar? Estamos aquí para ayudar." },
  "contact.getInTouch": { EN: "Get in touch", ES: "Ponte en contacto" },
  "contact.formIntro": { EN: "Fill out the form and we will respond as soon as possible. For urgent matters related to fraud reports, please select \"Observatory\" as the subject.", ES: "Llena el formulario y responderemos lo antes posible. Para asuntos urgentes relacionados con reportes de fraude, selecciona \"Observatorio\" como asunto." },
  "contact.email": { EN: "Email", ES: "Correo electrónico" },
  "contact.location": { EN: "Location", ES: "Ubicación" },
  "contact.florida": { EN: "Florida, United States", ES: "Florida, Estados Unidos" },
  "contact.legalNote": { EN: "For legal advice about your specific immigration situation, please consult a licensed attorney. We do not provide legal counsel.", ES: "Para asesoramiento legal sobre tu situación migratoria específica, consulta a un abogado licenciado. No proporcionamos asesoría legal." },
  "contact.yourName": { EN: "Your name", ES: "Tu nombre" },
  "contact.emailAddress": { EN: "Email address", ES: "Correo electrónico" },
  "contact.subject": { EN: "Subject", ES: "Asunto" },
  "contact.selectSubject": { EN: "Select a subject", ES: "Selecciona un asunto" },
  "contact.subjectGeneral": { EN: "General question", ES: "Pregunta general" },
  "contact.subjectMedia": { EN: "Media inquiry", ES: "Consulta de medios" },
  "contact.subjectObservatory": { EN: "Report to Observatory (OEAM)", ES: "Reportar al Observatorio (OEAM)" },
  "contact.subjectVolunteer": { EN: "Volunteer or membership", ES: "Voluntariado o membresía" },
  "contact.subjectOther": { EN: "Other", ES: "Otro" },
  "contact.message": { EN: "Message", ES: "Mensaje" },
  "contact.messagePlaceholder": { EN: "How can we help you?", ES: "¿Cómo podemos ayudarte?" },
  "contact.subscribe": { EN: "I would like to receive updates by email about your work and opportunities to get involved.", ES: "Me gustaría recibir actualizaciones por correo electrónico sobre su trabajo y oportunidades para participar." },
  "contact.send": { EN: "Send message", ES: "Enviar mensaje" },
  "contact.successTitle": { EN: "Message sent successfully!", ES: "¡Mensaje enviado exitosamente!" },
  "contact.successDesc": { EN: "Thank you for contacting us. We have received your message and will respond as soon as possible.", ES: "Gracias por contactarnos. Hemos recibido tu mensaje y responderemos lo antes posible." },
  "contact.sendAnother": { EN: "Send another message", ES: "Enviar otro mensaje" },
  "toast.messageSent": { EN: "Message sent!", ES: "¡Mensaje enviado!" },
  "toast.messageDesc": { EN: "Thank you for contacting us. We will respond soon.", ES: "Gracias por contactarnos. Responderemos pronto." },

  // Take Action Page
  "takeAction.backToSite": { EN: "Back to main site", ES: "Volver al sitio principal" },
  "takeAction.title": { EN: "Take action for Cuban freedom today", ES: "Toma acción por la libertad cubana hoy" },
  "takeAction.desc": { EN: "Complete your one-time or monthly donation in a few secure steps. Your support defends the Cuban Adjustment Act and protects Cuban migrants from fraud and abuse.", ES: "Completa tu donación única o mensual en unos pocos pasos seguros. Tu apoyo defiende la Ley de Ajuste Cubano y protege a los migrantes cubanos del fraude y abuso." },
  "takeAction.privacyNote": { EN: "We protect your data and use encrypted payment processing. We never sell your personal information.", ES: "Protegemos tus datos y usamos procesamiento de pago encriptado. Nunca vendemos tu información personal." },
  "takeAction.disclaimer": { EN: "This website provides information and advocacy. It does not replace legal counsel. For legal advice, please consult a licensed attorney.", ES: "Este sitio web proporciona información y defensa. No reemplaza el asesoramiento legal. Para asesoría legal, consulta a un abogado licenciado." },
  "takeAction.footer": { EN: "A non-profit organization under Florida law.", ES: "Una organización sin fines de lucro bajo la ley de Florida." },

  // Donation Wizard
  "donation.step": { EN: "Step", ES: "Paso" },
  "donation.of": { EN: "of", ES: "de" },
  "donation.step1Title": { EN: "Choose your donation", ES: "Elige tu donación" },
  "donation.step2Title": { EN: "Your information", ES: "Tu información" },
  "donation.step3Title": { EN: "Confirm your donation", ES: "Confirma tu donación" },
  "donation.oneTime": { EN: "One-time", ES: "Única" },
  "donation.monthly": { EN: "Monthly", ES: "Mensual" },
  "donation.selectAmount": { EN: "Select amount", ES: "Selecciona cantidad" },
  "donation.otherAmount": { EN: "Other amount", ES: "Otra cantidad" },
  "donation.enterAmount": { EN: "Enter amount", ES: "Ingresa cantidad" },
  "donation.paymentMethod": { EN: "Payment method", ES: "Método de pago" },
  "donation.creditCard": { EN: "Credit card", ES: "Tarjeta de crédito" },
  "donation.bankAccount": { EN: "Bank account", ES: "Cuenta bancaria" },
  "donation.continue": { EN: "Continue", ES: "Continuar" },
  "donation.secureNote": { EN: "Secure and encrypted processing. You can change or cancel a monthly donation at any time.", ES: "Procesamiento seguro y encriptado. Puedes cambiar o cancelar una donación mensual en cualquier momento." },
  "donation.firstName": { EN: "First name", ES: "Nombre" },
  "donation.lastName": { EN: "Last name", ES: "Apellido" },
  "donation.email": { EN: "Email", ES: "Correo electrónico" },
  "donation.country": { EN: "Country", ES: "País" },
  "donation.selectCountry": { EN: "Select country", ES: "Selecciona país" },
  "donation.acceptTerms": { EN: "I accept the terms and conditions and privacy policy", ES: "Acepto los términos y condiciones y la política de privacidad" },
  "donation.cardDetails": { EN: "Card details", ES: "Datos de la tarjeta" },
  "donation.bankDetails": { EN: "Bank details", ES: "Datos bancarios" },
  "donation.cardNumber": { EN: "Card number", ES: "Número de tarjeta" },
  "donation.expiry": { EN: "Expiry", ES: "Vencimiento" },
  "donation.zip": { EN: "ZIP", ES: "Código postal" },
  "donation.accountHolder": { EN: "Account holder name", ES: "Nombre del titular" },
  "donation.routingNumber": { EN: "Routing number", ES: "Número de ruta" },
  "donation.accountNumber": { EN: "Account number", ES: "Número de cuenta" },
  "donation.accountType": { EN: "Account type", ES: "Tipo de cuenta" },
  "donation.checking": { EN: "Checking", ES: "Corriente" },
  "donation.savings": { EN: "Savings", ES: "Ahorros" },
  "donation.back": { EN: "Back", ES: "Atrás" },
  "donation.reviewDonation": { EN: "Review donation", ES: "Revisar donación" },
  "donation.summary": { EN: "Donation summary", ES: "Resumen de donación" },
  "donation.type": { EN: "Type", ES: "Tipo" },
  "donation.amount": { EN: "Amount", ES: "Cantidad" },
  "donation.method": { EN: "Method", ES: "Método" },
  "donation.yourInfo": { EN: "Your info", ES: "Tu información" },
  "donation.change": { EN: "Change", ES: "Cambiar" },
  "donation.receiptOptIn": { EN: "Send me a receipt and occasional updates by email.", ES: "Envíame un recibo y actualizaciones ocasionales por correo electrónico." },
  "donation.completeDonation": { EN: "Complete donation", ES: "Completar donación" },
  "donation.thankYou": { EN: "Thank you for your donation!", ES: "¡Gracias por tu donación!" },
  "donation.thankYouDesc": { EN: "Your {amount} {type} donation helps us defend the rights of Cuban migrants and fight against fraud and abuse.", ES: "Tu donación {type} de {amount} nos ayuda a defender los derechos de los migrantes cubanos y luchar contra el fraude y abuso." },
  "donation.share": { EN: "Share this page", ES: "Compartir esta página" },
  "donation.shareText": { EN: "Support Cuban migrants - donate to Defenders of the CAA", ES: "Apoya a los migrantes cubanos - dona a Defensores de la CAA" },
  "donation.successMessage": { EN: "Your generosity helps us defend the rights of Cuban migrants and fight against fraud and abuse. A receipt has been sent to your email.", ES: "Tu generosidad nos ayuda a defender los derechos de los migrantes cubanos y luchar contra el fraude y abuso. Se ha enviado un recibo a tu correo electrónico." },
  "donation.step2TitleSimple": { EN: "Your information", ES: "Tu información" },
  "donation.emailRequired": { EN: "Email is required", ES: "El correo electrónico es requerido" },
  "donation.checkoutError": { EN: "Unable to start checkout. Please try again.", ES: "No se pudo iniciar el pago. Por favor intenta de nuevo." },
  "donation.processing": { EN: "Processing...", ES: "Procesando..." },
  "donation.proceedToPayment": { EN: "Proceed to payment", ES: "Proceder al pago" },
  "donation.stripeSecure": { EN: "You will be redirected to Stripe's secure payment page.", ES: "Serás redirigido a la página de pago segura de Stripe." },

  // Footer
  "footer.brand": { EN: "Defenders of the CAA", ES: "Defensores de la CAA" },
  "footer.brandSub": { EN: "and Freedom, Inc.", ES: "y la Libertad, Inc." },
  "footer.desc": { EN: "A non-partisan, community-based non-profit organization defending the rights of Cuban migrants through education, advocacy, and community support.", ES: "Una organización sin fines de lucro comunitaria y no partidista que defiende los derechos de los migrantes cubanos a través de la educación, defensa y apoyo comunitario." },
  "footer.quickLinks": { EN: "Quick Links", ES: "Enlaces Rápidos" },
  "footer.aboutUs": { EN: "About Us", ES: "Nosotros" },
  "footer.ourWork": { EN: "Our Work", ES: "Nuestro Trabajo" },
  "footer.blogNews": { EN: "Blog & News", ES: "Blog y Noticias" },
  "footer.resources": { EN: "Resources", ES: "Recursos" },
  "footer.getInvolved": { EN: "Get Involved", ES: "Participa" },
  "footer.donate": { EN: "Donate", ES: "Donar" },
  "footer.becomeMember": { EN: "Become a Member", ES: "Hazte Miembro" },
  "footer.volunteer": { EN: "Volunteer", ES: "Voluntariado" },
  "footer.contactUs": { EN: "Contact Us", ES: "Contáctanos" },
  "footer.legal": { EN: "Legal", ES: "Legal" },
  "footer.legalDesc": { EN: "Defenders of the CAA and Freedom, Inc. is a non-profit organization under Chapter 617 of the Florida Statutes, recognized as a 501(c)(3) tax-exempt organization.", ES: "Defensores de la CAA y la Libertad, Inc. es una organización sin fines de lucro bajo el Capítulo 617 de los Estatutos de Florida, reconocida como organización exenta de impuestos 501(c)(3)." },
  "footer.legalDisclaimer": { EN: "This website does not provide legal advice. For legal counsel, please consult a licensed attorney.", ES: "Este sitio web no proporciona asesoramiento legal. Para asesoría legal, consulta a un abogado licenciado." },
  "footer.allRights": { EN: "All rights reserved.", ES: "Todos los derechos reservados." },
  "footer.privacy": { EN: "Privacy Policy", ES: "Política de Privacidad" },
  "footer.terms": { EN: "Terms of Use", ES: "Términos de Uso" },

  // Countries
  "country.us": { EN: "United States", ES: "Estados Unidos" },
  "country.canada": { EN: "Canada", ES: "Canadá" },
  "country.mexico": { EN: "Mexico", ES: "México" },
  "country.cuba": { EN: "Cuba", ES: "Cuba" },
  "country.spain": { EN: "Spain", ES: "España" },
  "country.other": { EN: "Other", ES: "Otro" },

  // Donation checkbox links
  "donation.acceptTermsPrefix": { EN: "I accept the", ES: "Acepto los" },
  "donation.termsLink": { EN: "terms and conditions", ES: "términos y condiciones" },
  "donation.acceptTermsAnd": { EN: "and", ES: "y la" },
  "donation.privacyLink": { EN: "privacy policy", ES: "política de privacidad" },

  // Terms and Conditions Page
  "terms.title": { EN: "Terms and Conditions", ES: "Términos y Condiciones" },
  "terms.lastUpdated": { EN: "Last updated: December 2024", ES: "Última actualización: Diciembre 2024" },
  "terms.section1.title": { EN: "Use of the Site", ES: "Uso del Sitio" },
  "terms.section1.content": { EN: "This website is owned and operated by Defenders of the CAA and Freedom, Inc. By accessing or using the site, you agree to these Terms and Conditions. The purpose of this website is to provide information about the Cuban Adjustment Act, civic education, and community support. You agree to use it lawfully and not to harm our systems or violate any laws.", ES: "Este sitio web es propiedad y está operado por Defensores de la CAA y la Libertad, Inc. Al acceder o utilizar el sitio, usted acepta estos Términos y Condiciones. El propósito de este sitio web es proporcionar información sobre la Ley de Ajuste Cubano, educación cívica y apoyo comunitario. Usted acepta usarlo de manera legal y no dañar nuestros sistemas ni violar ninguna ley." },
  "terms.section2.title": { EN: "Intellectual Property", ES: "Propiedad Intelectual" },
  "terms.section2.content": { EN: "All content on this site, including text, graphics, logos, and images, is the property of Defenders of the CAA and Freedom, Inc. or its content suppliers and is protected by copyright and trademark laws. You may not copy, reproduce, distribute, or create derivative works without prior written permission.", ES: "Todo el contenido de este sitio, incluidos textos, gráficos, logotipos e imágenes, es propiedad de Defensores de la CAA y la Libertad, Inc. o sus proveedores de contenido y está protegido por las leyes de derechos de autor y marcas registradas. No puede copiar, reproducir, distribuir o crear obras derivadas sin permiso previo por escrito." },
  "terms.section3.title": { EN: "Donations", ES: "Donaciones" },
  "terms.section3.content": { EN: "All donations are voluntary and non-refundable. Funds are used exclusively for institutional purposes aligned with our mission, including education, community support, and advocacy. Donors will receive electronic confirmation of their contributions.", ES: "Todas las donaciones son voluntarias y no reembolsables. Los fondos se utilizan exclusivamente para fines institucionales alineados con nuestra misión, incluyendo educación, apoyo comunitario y defensa. Los donantes recibirán confirmación electrónica de sus contribuciones." },
  "terms.section4.title": { EN: "No Legal Advice", ES: "No Asesoramiento Legal" },
  "terms.section4.content": { EN: "The information provided on this website is for general educational purposes only and should not be construed as legal advice. For specific legal matters, please consult a licensed immigration attorney. We do not provide individual legal representation or counsel.", ES: "La información proporcionada en este sitio web es solo para fines educativos generales y no debe interpretarse como asesoramiento legal. Para asuntos legales específicos, consulte a un abogado de inmigración licenciado. No proporcionamos representación legal individual ni asesoría." },
  "terms.section5.title": { EN: "Limitation of Liability", ES: "Limitación de Responsabilidad" },
  "terms.section5.content": { EN: "Defenders of the CAA and Freedom, Inc. shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of this website or reliance on any information provided herein. We do not guarantee the accuracy, completeness, or timeliness of the information on our site.", ES: "Defensores de la CAA y la Libertad, Inc. no será responsable de ningún daño directo, indirecto, incidental, especial o consecuente que surja de su uso de este sitio web o de la confianza en cualquier información proporcionada aquí. No garantizamos la exactitud, integridad o actualidad de la información en nuestro sitio." },
  "terms.section6.title": { EN: "Third-Party Links", ES: "Enlaces a Terceros" },
  "terms.section6.content": { EN: "This website may contain links to third-party websites. These links are provided for convenience only. We do not endorse or control these external sites and are not responsible for their content or privacy practices.", ES: "Este sitio web puede contener enlaces a sitios web de terceros. Estos enlaces se proporcionan solo por conveniencia. No respaldamos ni controlamos estos sitios externos y no somos responsables de su contenido o prácticas de privacidad." },
  "terms.section7.title": { EN: "Privacy", ES: "Privacidad" },
  "terms.section7.content": { EN: "Your privacy is important to us. Please review our Privacy Policy for information on how we collect, use, and protect your personal data.", ES: "Su privacidad es importante para nosotros. Por favor revise nuestra Política de Privacidad para información sobre cómo recopilamos, usamos y protegemos sus datos personales." },
  "terms.section8.title": { EN: "Modifications", ES: "Modificaciones" },
  "terms.section8.content": { EN: "We reserve the right to modify these Terms and Conditions at any time. Changes will be posted on this page with an updated effective date. Your continued use of the site after any changes constitutes acceptance of the new terms.", ES: "Nos reservamos el derecho de modificar estos Términos y Condiciones en cualquier momento. Los cambios se publicarán en esta página con una fecha de vigencia actualizada. Su uso continuado del sitio después de cualquier cambio constituye la aceptación de los nuevos términos." },
  "terms.section9.title": { EN: "Governing Law", ES: "Ley Aplicable" },
  "terms.section9.content": { EN: "These Terms and Conditions are governed by the laws of the State of Florida, United States, without regard to conflict of law principles.", ES: "Estos Términos y Condiciones se rigen por las leyes del Estado de Florida, Estados Unidos, sin tener en cuenta los principios de conflicto de leyes." },
  "terms.section10.title": { EN: "Contact", ES: "Contacto" },
  "terms.section10.content": { EN: "If you have any questions about these Terms and Conditions, please contact us at info@defensoresdelacaa.org.", ES: "Si tiene alguna pregunta sobre estos Términos y Condiciones, contáctenos en info@defensoresdelacaa.org." },

  // Privacy Policy Page
  "privacy.title": { EN: "Privacy Policy", ES: "Política de Privacidad" },
  "privacy.lastUpdated": { EN: "Last updated: December 2024", ES: "Última actualización: Diciembre 2024" },
  "privacy.intro": { EN: "Defenders of the CAA and Freedom, Inc. is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and protect your personal information when you visit our website or interact with us.", ES: "Defensores de la CAA y la Libertad, Inc. está comprometido con la protección de su privacidad. Esta Política de Privacidad explica cómo recopilamos, usamos y protegemos su información personal cuando visita nuestro sitio web o interactúa con nosotros." },
  "privacy.section1.title": { EN: "Information We Collect", ES: "Información que Recopilamos" },
  "privacy.section1.content": { EN: "We may collect the following types of information:", ES: "Podemos recopilar los siguientes tipos de información:" },
  "privacy.section1.item1": { EN: "Personal information you provide voluntarily, such as your name, email address, and country when making a donation or signing up as a member.", ES: "Información personal que proporciona voluntariamente, como su nombre, dirección de correo electrónico y país al hacer una donación o registrarse como miembro." },
  "privacy.section1.item2": { EN: "Technical data such as IP address, browser type, and device information for analytics purposes.", ES: "Datos técnicos como dirección IP, tipo de navegador e información del dispositivo para fines analíticos." },
  "privacy.section1.item3": { EN: "Donation and payment information processed securely through our third-party payment processor (Stripe).", ES: "Información de donación y pago procesada de forma segura a través de nuestro procesador de pagos de terceros (Stripe)." },
  "privacy.section2.title": { EN: "How We Use Your Information", ES: "Cómo Usamos su Información" },
  "privacy.section2.content": { EN: "We use your information for the following purposes:", ES: "Usamos su información para los siguientes propósitos:" },
  "privacy.section2.item1": { EN: "To process donations and send receipts.", ES: "Para procesar donaciones y enviar recibos." },
  "privacy.section2.item2": { EN: "To communicate with you about our programs, events, and updates (if you opt in).", ES: "Para comunicarnos con usted sobre nuestros programas, eventos y actualizaciones (si opta por recibirlos)." },
  "privacy.section2.item3": { EN: "To improve our website and services through analytics.", ES: "Para mejorar nuestro sitio web y servicios mediante análisis." },
  "privacy.section2.item4": { EN: "To comply with legal obligations and protect our organization.", ES: "Para cumplir con obligaciones legales y proteger nuestra organización." },
  "privacy.section3.title": { EN: "Information Sharing", ES: "Compartición de Información" },
  "privacy.section3.content": { EN: "We do not sell, rent, or trade your personal information to third parties. We may share your information with:", ES: "No vendemos, alquilamos ni intercambiamos su información personal con terceros. Podemos compartir su información con:" },
  "privacy.section3.item1": { EN: "Payment processors (Stripe) to handle donations securely.", ES: "Procesadores de pago (Stripe) para manejar donaciones de forma segura." },
  "privacy.section3.item2": { EN: "Service providers who assist with website operations, subject to confidentiality agreements.", ES: "Proveedores de servicios que asisten con las operaciones del sitio web, sujetos a acuerdos de confidencialidad." },
  "privacy.section3.item3": { EN: "Law enforcement or government agencies when required by law.", ES: "Autoridades policiales o agencias gubernamentales cuando lo requiera la ley." },
  "privacy.section4.title": { EN: "Data Security", ES: "Seguridad de los Datos" },
  "privacy.section4.content": { EN: "We implement appropriate technical and organizational measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction. Our website uses SSL encryption for secure data transmission.", ES: "Implementamos medidas técnicas y organizativas apropiadas para proteger su información personal del acceso no autorizado, alteración, divulgación o destrucción. Nuestro sitio web utiliza encriptación SSL para la transmisión segura de datos." },
  "privacy.section5.title": { EN: "Data Retention", ES: "Retención de Datos" },
  "privacy.section5.content": { EN: "We retain your personal information only for as long as necessary to fulfill the purposes outlined in this policy or as required by law. Donation records are kept in accordance with nonprofit reporting requirements.", ES: "Retenemos su información personal solo durante el tiempo necesario para cumplir con los propósitos descritos en esta política o según lo requiera la ley. Los registros de donaciones se mantienen de acuerdo con los requisitos de informes para organizaciones sin fines de lucro." },
  "privacy.section6.title": { EN: "Your Rights", ES: "Sus Derechos" },
  "privacy.section6.content": { EN: "Depending on your location, you may have the following rights regarding your personal data:", ES: "Dependiendo de su ubicación, puede tener los siguientes derechos con respecto a sus datos personales:" },
  "privacy.section6.item1": { EN: "Access: Request a copy of the personal information we hold about you.", ES: "Acceso: Solicitar una copia de la información personal que tenemos sobre usted." },
  "privacy.section6.item2": { EN: "Correction: Request correction of inaccurate or incomplete data.", ES: "Corrección: Solicitar la corrección de datos inexactos o incompletos." },
  "privacy.section6.item3": { EN: "Deletion: Request deletion of your personal information, subject to legal retention requirements.", ES: "Eliminación: Solicitar la eliminación de su información personal, sujeto a requisitos legales de retención." },
  "privacy.section7.title": { EN: "Children", ES: "Niños" },
  "privacy.section7.content": { EN: "Our website is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe we have collected information from a child, please contact us immediately.", ES: "Nuestro sitio web no está dirigido a niños menores de 13 años. No recopilamos intencionalmente información personal de niños. Si cree que hemos recopilado información de un niño, contáctenos inmediatamente." },
  "privacy.section8.title": { EN: "Changes to This Policy", ES: "Cambios a esta Política" },
  "privacy.section8.content": { EN: "We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated effective date. We encourage you to review this policy periodically.", ES: "Podemos actualizar esta Política de Privacidad de vez en cuando. Los cambios se publicarán en esta página con una fecha de vigencia actualizada. Le recomendamos revisar esta política periódicamente." },
  "privacy.section9.title": { EN: "Contact", ES: "Contacto" },
  "privacy.section9.content": { EN: "If you have any questions about this Privacy Policy or wish to exercise your rights, please contact us at info@defensoresdelacaa.org.", ES: "Si tiene alguna pregunta sobre esta Política de Privacidad o desea ejercer sus derechos, contáctenos en info@defensoresdelacaa.org." },

  // Consent Popup
  "consent.title": { EN: "Welcome to our website", ES: "Bienvenido a nuestro sitio web" },
  "consent.description": { EN: "To continue using this website, you must agree to our", ES: "Para continuar usando este sitio web, debe aceptar nuestros" },
  "consent.termsLink": { EN: "Terms and Conditions", ES: "Términos y Condiciones" },
  "consent.and": { EN: "and", ES: "y" },
  "consent.privacyLink": { EN: "Privacy Policy", ES: "Política de Privacidad" },
  "consent.accept": { EN: "I Accept", ES: "Acepto" },
  "consent.decline": { EN: "I Do Not Accept", ES: "No Acepto" },
  "consent.declinedTitle": { EN: "Access Denied", ES: "Acceso Denegado" },
  "consent.declinedDescription": { EN: "You cannot use this website without accepting our Terms and Conditions and Privacy Policy. If you change your mind, you can reconsider your decision.", ES: "No puede usar este sitio web sin aceptar nuestros Términos y Condiciones y Política de Privacidad. Si cambia de opinión, puede reconsiderar su decisión." },
  "consent.reconsider": { EN: "Reconsider", ES: "Reconsiderar" },

  // Video Modal
  "video.title": { EN: "Our Mission & Impact", ES: "Nuestra Misión e Impacto" },
  "video.description": { EN: "Watch what we do and what we've achieved at Defenders of the CAA and Freedom. This video showcases our commitment to protecting Cuban migrants and defending their rights.", ES: "Mira lo que hacemos y lo que hemos logrado en Defensores de la CAA y la Libertad. Este video muestra nuestro compromiso con la protección de los migrantes cubanos y la defensa de sus derechos." },
  "header.watchVideo": { EN: "Watch Video", ES: "Ver Video" },
};

// Detect browser language
const detectLanguage = (): Language => {
  const saved = localStorage.getItem("language");
  if (saved === "EN" || saved === "ES") return saved;
  
  const browserLang = navigator.language || (navigator as any).userLanguage;
  if (browserLang?.startsWith("es")) return "ES";
  return "EN";
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(detectLanguage);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
